
spring:
  datasource:
    master:
      url: jdbc:mysql://58.87.83.245:24311/test1?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: qwer1234.
    slave:
      url: jdbc:mysql://58.87.83.245:24311/test?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: qwer1234.
#    url: jdbc:mysql://58.87.83.245:24311/test?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: qwer1234.
#读写分离配置


  redis:
    database: 0
    host: 10.231.96.6
    port: 6379
    password: e3Rhb&5ha8dIP4_yB
    ssl: false
    timeout: 5000
#    cluster:
#      nodes:
#        - 127.0.0.1
#    sentinel:
#      master:
#      nodes:
#        - 127.0.0.1


# mybatis
#测试多数据源关闭单个数据源mybatis配置，如果要关闭多数据源则DbSourceConfig去掉@Config
#mybatis:
#  config-location: classpath:mybatis/config.xml
#  mapper-locations: classpath*:mybatis/mapper/**/*.xml

#多数据源配置
mybatis:
  typeAliasesPackage: com.springboot.tao.bean.db
  mapperLocations: classpath*:mybatis/mapper/**/*.xml



#elasticsearch
elasticsearch:
  host: 172.23.95.14
  port: 9200
  name: elastic
  password: 123qwe

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        max-age: 300m
      timeout: 60m

#properties
test1:
  mysql:
    name: taozhiwei1
    password: 1111
test2:
  mysql:
    name: taozhiwei2
    password: 22222

#logging:
#  config: classpath:log4j2-dev.xml