
spring:
  datasource:
    url: jdbc:mysql://49.233.18.164:3306/test?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


# mybatis
mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

