
spring:
  datasource:
    url: jdbc:mysql://49.233.18.164:3306/test?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: apc-innismall-stg-redis.redis.cache.chinacloudapi.cn
    port: 6379
    password: pRK7HxSwaGZPumJm6OGoNp2vZobjzXO0+SslBkkTIRE=
    ssl: false
    timeout: 5000
#    cluster:
#      nodes:
#        - 127.0.0.1
#    sentinel:
#      master:
#      nodes:
#        - 127.0.0.1


# mybatis
mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

#elasticsearch
elasticsearch:
  host: 172.23.95.14
  port: 9200
  name: elastic
  password: 123qwe

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        max-age: 300m
      timeout: 60m

